// Mocks generated by Mockito from annotations
// in app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;

import 'package:app/core/domain/domain.dart' as _i2;
import 'package:app/features/auth/data/auth_repository.dart' as _i6;
import 'package:app/features/auth/data/member_repository.dart' as _i8;
import 'package:app/features/goals/application/goal_service.dart' as _i13;
import 'package:app/features/goals/data/goals_repository.dart' as _i10;
import 'package:app/features/goals/data/models.dart' as _i11;
import 'package:app/features/goals/domain/goal.dart' as _i4;
import 'package:app/features/goals/domain/goal_status.dart' as _i12;
import 'package:app/features/groups/data/groups_repository.dart' as _i9;
import 'package:app/features/groups/domain/group.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:supabase/supabase.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMember_0 extends _i1.SmartFake implements _i2.Member {
  _FakeMember_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGroup_1 extends _i1.SmartFake implements _i3.Group {
  _FakeGroup_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoal_2 extends _i1.SmartFake implements _i4.Goal {
  _FakeGoal_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_3 extends _i1.SmartFake
    implements _i5.FunctionsClient {
  _FakeFunctionsClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_4 extends _i1.SmartFake
    implements _i5.SupabaseStorageClient {
  _FakeSupabaseStorageClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_5 extends _i1.SmartFake
    implements _i5.RealtimeClient {
  _FakeRealtimeClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_6 extends _i1.SmartFake
    implements _i5.PostgrestClient {
  _FakePostgrestClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_7 extends _i1.SmartFake implements _i5.GoTrueClient {
  _FakeGoTrueClient_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_8 extends _i1.SmartFake
    implements _i5.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_9 extends _i1.SmartFake
    implements _i5.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_10<T1> extends _i1.SmartFake
    implements _i5.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_11 extends _i1.SmartFake
    implements _i5.RealtimeChannel {
  _FakeRealtimeChannel_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  @override
  _i7.Stream<_i5.AuthState> authStateChanges() => (super.noSuchMethod(
    Invocation.method(#authStateChanges, []),
    returnValue: _i7.Stream<_i5.AuthState>.empty(),
    returnValueForMissingStub: _i7.Stream<_i5.AuthState>.empty(),
  ) as _i7.Stream<_i5.AuthState>);

  @override
  _i7.Future<void> signUp({
    required String? name,
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#signUp, [], {
      #name: name,
      #email: email,
      #password: password,
    }),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<void> signIn({
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#signIn, [], {#email: email, #password: password}),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
    Invocation.method(#signOut, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);
}

/// A class which mocks [MemberRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepository extends _i1.Mock implements _i8.MemberRepository {
  @override
  _i7.Future<_i2.Member> fetchMember(String? id) => (super.noSuchMethod(
    Invocation.method(#fetchMember, [id]),
    returnValue: _i7.Future<_i2.Member>.value(
      _FakeMember_0(this, Invocation.method(#fetchMember, [id])),
    ),
    returnValueForMissingStub: _i7.Future<_i2.Member>.value(
      _FakeMember_0(this, Invocation.method(#fetchMember, [id])),
    ),
  ) as _i7.Future<_i2.Member>);
}

/// A class which mocks [GroupsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupsRepository extends _i1.Mock implements _i9.GroupsRepository {
  @override
  _i7.Future<_i3.Group> createGroup(String? name) => (super.noSuchMethod(
    Invocation.method(#createGroup, [name]),
    returnValue: _i7.Future<_i3.Group>.value(
      _FakeGroup_1(this, Invocation.method(#createGroup, [name])),
    ),
    returnValueForMissingStub: _i7.Future<_i3.Group>.value(
      _FakeGroup_1(this, Invocation.method(#createGroup, [name])),
    ),
  ) as _i7.Future<_i3.Group>);

  @override
  _i7.Future<_i3.Group> joinGroup(String? groupId) => (super.noSuchMethod(
    Invocation.method(#joinGroup, [groupId]),
    returnValue: _i7.Future<_i3.Group>.value(
      _FakeGroup_1(this, Invocation.method(#joinGroup, [groupId])),
    ),
    returnValueForMissingStub: _i7.Future<_i3.Group>.value(
      _FakeGroup_1(this, Invocation.method(#joinGroup, [groupId])),
    ),
  ) as _i7.Future<_i3.Group>);

  @override
  _i7.Future<_i3.Group> fetchGroup(String? id) => (super.noSuchMethod(
    Invocation.method(#fetchGroup, [id]),
    returnValue: _i7.Future<_i3.Group>.value(
      _FakeGroup_1(this, Invocation.method(#fetchGroup, [id])),
    ),
    returnValueForMissingStub: _i7.Future<_i3.Group>.value(
      _FakeGroup_1(this, Invocation.method(#fetchGroup, [id])),
    ),
  ) as _i7.Future<_i3.Group>);

  @override
  _i7.Future<List<_i2.Member>> fetchMembers(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(#fetchMembers, [groupId]),
        returnValue: _i7.Future<List<_i2.Member>>.value(<_i2.Member>[]),
        returnValueForMissingStub: _i7.Future<List<_i2.Member>>.value(
          <_i2.Member>[],
        ),
      ) as _i7.Future<List<_i2.Member>>);
}

/// A class which mocks [GoalsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsRepository extends _i1.Mock implements _i10.GoalsRepository {
  @override
  _i7.Future<List<_i4.Goal>> fetchGoals({
    required String? ownerId,
    required _i2.Period? period,
  }) => (super.noSuchMethod(
    Invocation.method(#fetchGoals, [], {#ownerId: ownerId, #period: period}),
    returnValue: _i7.Future<List<_i4.Goal>>.value(<_i4.Goal>[]),
    returnValueForMissingStub: _i7.Future<List<_i4.Goal>>.value(<_i4.Goal>[]),
  ) as _i7.Future<List<_i4.Goal>>);

  @override
  _i7.Future<List<_i4.Goal>> fetchGoalsBefore({
    required String? ownerId,
    required _i2.GoalType? type,
    required DateTime? before,
  }) => (super.noSuchMethod(
    Invocation.method(#fetchGoalsBefore, [], {
      #ownerId: ownerId,
      #type: type,
      #before: before,
    }),
    returnValue: _i7.Future<List<_i4.Goal>>.value(<_i4.Goal>[]),
    returnValueForMissingStub: _i7.Future<List<_i4.Goal>>.value(<_i4.Goal>[]),
  ) as _i7.Future<List<_i4.Goal>>);

  @override
  _i7.Future<_i4.Goal> createGoal(_i11.CreateGoalCommand? command) =>
      (super.noSuchMethod(
        Invocation.method(#createGoal, [command]),
        returnValue: _i7.Future<_i4.Goal>.value(
          _FakeGoal_2(this, Invocation.method(#createGoal, [command])),
        ),
        returnValueForMissingStub: _i7.Future<_i4.Goal>.value(
          _FakeGoal_2(this, Invocation.method(#createGoal, [command])),
        ),
      ) as _i7.Future<_i4.Goal>);

  @override
  _i7.Future<_i4.Goal> setStatus(String? goalId, _i12.GoalStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(#setStatus, [goalId, status]),
        returnValue: _i7.Future<_i4.Goal>.value(
          _FakeGoal_2(this, Invocation.method(#setStatus, [goalId, status])),
        ),
        returnValueForMissingStub: _i7.Future<_i4.Goal>.value(
          _FakeGoal_2(this, Invocation.method(#setStatus, [goalId, status])),
        ),
      ) as _i7.Future<_i4.Goal>);

  @override
  _i7.Future<_i4.Goal> verify(String? goalId) => (super.noSuchMethod(
    Invocation.method(#verify, [goalId]),
    returnValue: _i7.Future<_i4.Goal>.value(
      _FakeGoal_2(this, Invocation.method(#verify, [goalId])),
    ),
    returnValueForMissingStub: _i7.Future<_i4.Goal>.value(
      _FakeGoal_2(this, Invocation.method(#verify, [goalId])),
    ),
  ) as _i7.Future<_i4.Goal>);

  @override
  _i7.Future<_i4.Goal> updateTitle(String? goalId, String? title) =>
      (super.noSuchMethod(
        Invocation.method(#updateTitle, [goalId, title]),
        returnValue: _i7.Future<_i4.Goal>.value(
          _FakeGoal_2(this, Invocation.method(#updateTitle, [goalId, title])),
        ),
        returnValueForMissingStub: _i7.Future<_i4.Goal>.value(
          _FakeGoal_2(this, Invocation.method(#updateTitle, [goalId, title])),
        ),
      ) as _i7.Future<_i4.Goal>);

  @override
  _i7.Future<void> deleteGoal(String? goalId) => (super.noSuchMethod(
    Invocation.method(#deleteGoal, [goalId]),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);
}

/// A class which mocks [GoalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalService extends _i1.Mock implements _i13.GoalService {
  @override
  _i7.Future<_i4.Goal> createGoal({
    required String? title,
    required _i2.GoalType? type,
  }) => (super.noSuchMethod(
    Invocation.method(#createGoal, [], {#title: title, #type: type}),
    returnValue: _i7.Future<_i4.Goal>.value(
      _FakeGoal_2(
        this,
        Invocation.method(#createGoal, [], {#title: title, #type: type}),
      ),
    ),
    returnValueForMissingStub: _i7.Future<_i4.Goal>.value(
      _FakeGoal_2(
        this,
        Invocation.method(#createGoal, [], {#title: title, #type: type}),
      ),
    ),
  ) as _i7.Future<_i4.Goal>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i5.SupabaseClient {
  @override
  _i5.FunctionsClient get functions => (super.noSuchMethod(
    Invocation.getter(#functions),
    returnValue: _FakeFunctionsClient_3(this, Invocation.getter(#functions)),
    returnValueForMissingStub: _FakeFunctionsClient_3(
      this,
      Invocation.getter(#functions),
    ),
  ) as _i5.FunctionsClient);

  @override
  _i5.SupabaseStorageClient get storage => (super.noSuchMethod(
    Invocation.getter(#storage),
    returnValue: _FakeSupabaseStorageClient_4(
      this,
      Invocation.getter(#storage),
    ),
    returnValueForMissingStub: _FakeSupabaseStorageClient_4(
      this,
      Invocation.getter(#storage),
    ),
  ) as _i5.SupabaseStorageClient);

  @override
  _i5.RealtimeClient get realtime => (super.noSuchMethod(
    Invocation.getter(#realtime),
    returnValue: _FakeRealtimeClient_5(this, Invocation.getter(#realtime)),
    returnValueForMissingStub: _FakeRealtimeClient_5(
      this,
      Invocation.getter(#realtime),
    ),
  ) as _i5.RealtimeClient);

  @override
  _i5.PostgrestClient get rest => (super.noSuchMethod(
    Invocation.getter(#rest),
    returnValue: _FakePostgrestClient_6(this, Invocation.getter(#rest)),
    returnValueForMissingStub: _FakePostgrestClient_6(
      this,
      Invocation.getter(#rest),
    ),
  ) as _i5.PostgrestClient);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
    Invocation.getter(#headers),
    returnValue: <String, String>{},
    returnValueForMissingStub: <String, String>{},
  ) as Map<String, String>);

  @override
  _i5.GoTrueClient get auth => (super.noSuchMethod(
    Invocation.getter(#auth),
    returnValue: _FakeGoTrueClient_7(this, Invocation.getter(#auth)),
    returnValueForMissingStub: _FakeGoTrueClient_7(
      this,
      Invocation.getter(#auth),
    ),
  ) as _i5.GoTrueClient);

  @override
  set functions(_i5.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i5.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i5.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i5.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? newHeaders) => super.noSuchMethod(
    Invocation.setter(#headers, newHeaders),
    returnValueForMissingStub: null,
  );

  @override
  _i5.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
    Invocation.method(#from, [table]),
    returnValue: _FakeSupabaseQueryBuilder_8(
      this,
      Invocation.method(#from, [table]),
    ),
    returnValueForMissingStub: _FakeSupabaseQueryBuilder_8(
      this,
      Invocation.method(#from, [table]),
    ),
  ) as _i5.SupabaseQueryBuilder);

  @override
  _i5.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
    Invocation.method(#schema, [schema]),
    returnValue: _FakeSupabaseQuerySchema_9(
      this,
      Invocation.method(#schema, [schema]),
    ),
    returnValueForMissingStub: _FakeSupabaseQuerySchema_9(
      this,
      Invocation.method(#schema, [schema]),
    ),
  ) as _i5.SupabaseQuerySchema);

  @override
  _i5.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) => (super.noSuchMethod(
    Invocation.method(#rpc, [fn], {#params: params, #get: get}),
    returnValue: _FakePostgrestFilterBuilder_10<T>(
      this,
      Invocation.method(#rpc, [fn], {#params: params, #get: get}),
    ),
    returnValueForMissingStub: _FakePostgrestFilterBuilder_10<T>(
      this,
      Invocation.method(#rpc, [fn], {#params: params, #get: get}),
    ),
  ) as _i5.PostgrestFilterBuilder<T>);

  @override
  _i5.RealtimeChannel channel(
    String? name, {
    _i5.RealtimeChannelConfig? opts = const _i5.RealtimeChannelConfig(),
  }) => (super.noSuchMethod(
    Invocation.method(#channel, [name], {#opts: opts}),
    returnValue: _FakeRealtimeChannel_11(
      this,
      Invocation.method(#channel, [name], {#opts: opts}),
    ),
    returnValueForMissingStub: _FakeRealtimeChannel_11(
      this,
      Invocation.method(#channel, [name], {#opts: opts}),
    ),
  ) as _i5.RealtimeChannel);

  @override
  List<_i5.RealtimeChannel> getChannels() => (super.noSuchMethod(
    Invocation.method(#getChannels, []),
    returnValue: <_i5.RealtimeChannel>[],
    returnValueForMissingStub: <_i5.RealtimeChannel>[],
  ) as List<_i5.RealtimeChannel>);

  @override
  _i7.Future<String> removeChannel(_i5.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(#removeChannel, [channel]),
        returnValue: _i7.Future<String>.value(
          _i14.dummyValue<String>(
            this,
            Invocation.method(#removeChannel, [channel]),
          ),
        ),
        returnValueForMissingStub: _i7.Future<String>.value(
          _i14.dummyValue<String>(
            this,
            Invocation.method(#removeChannel, [channel]),
          ),
        ),
      ) as _i7.Future<String>);

  @override
  _i7.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
    Invocation.method(#removeAllChannels, []),
    returnValue: _i7.Future<List<String>>.value(<String>[]),
    returnValueForMissingStub: _i7.Future<List<String>>.value(<String>[]),
  ) as _i7.Future<List<String>>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);
}
