// Mocks generated by Mockito from annotations
// in app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:app/core/domain/domain.dart' as _i2;
import 'package:app/features/auth/data/auth_repository.dart' as _i3;
import 'package:app/features/auth/data/member_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMember_0 extends _i1.SmartFake implements _i2.Member {
  _FakeMember_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Stream<_i5.AuthState> authStateChanges() => (super.noSuchMethod(
    Invocation.method(#authStateChanges, []),
    returnValue: _i4.Stream<_i5.AuthState>.empty(),
    returnValueForMissingStub: _i4.Stream<_i5.AuthState>.empty(),
  ) as _i4.Stream<_i5.AuthState>);

  @override
  _i4.Future<void> signUp({
    required String? name,
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#signUp, [], {
      #name: name,
      #email: email,
      #password: password,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> signIn({
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#signIn, [], {#email: email, #password: password}),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
    Invocation.method(#signOut, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}

/// A class which mocks [MemberRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepository extends _i1.Mock implements _i6.MemberRepository {
  @override
  _i4.Future<_i2.Member> fetchMember(String? id) => (super.noSuchMethod(
    Invocation.method(#fetchMember, [id]),
    returnValue: _i4.Future<_i2.Member>.value(
      _FakeMember_0(this, Invocation.method(#fetchMember, [id])),
    ),
    returnValueForMissingStub: _i4.Future<_i2.Member>.value(
      _FakeMember_0(this, Invocation.method(#fetchMember, [id])),
    ),
  ) as _i4.Future<_i2.Member>);
}
