import 'package:app/features/auth/data/auth_repository.dart';
import 'package:app/features/auth/data/member_repository.dart';
import 'package:mockito/annotations.dart';

/// Mocks for the whole suite, generated by `dart run build_runner build`.
///
/// `GenerateNiceMocks` gives every member a harmless default — null, an empty
/// stream, a completed future — so a test only stubs the calls it is about.
/// Add a `MockSpec` here when a new repository or service needs one.
@GenerateNiceMocks([MockSpec<AuthRepository>(), MockSpec<MemberRepository>()])
export 'mocks.mocks.dart';
