import 'package:app/features/auth/data/auth_repository.dart';
import 'package:app/features/auth/data/member_repository.dart';
import 'package:app/features/goals/application/goal_service.dart';
import 'package:app/features/goals/data/goals_repository.dart';
import 'package:app/features/groups/data/groups_repository.dart';
import 'package:mockito/annotations.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Mocks for the whole suite, generated by `dart run build_runner build`.
///
/// `GenerateNiceMocks` gives every member a harmless default — null, an empty
/// stream, a completed future — so a test only stubs the calls it is about.
/// Add a `MockSpec` here when a new repository or service needs one.
@GenerateNiceMocks([
  MockSpec<AuthRepository>(),
  MockSpec<MemberRepository>(),
  MockSpec<GroupsRepository>(),
  MockSpec<GoalsRepository>(),
  MockSpec<GoalService>(),
  MockSpec<SupabaseClient>(),
])
export 'mocks.mocks.dart';
